---
title: "Creating blurbs"
author: "Naren Srinivasan"
date: "11 January 2019"
output: html_document
---
output: 
  rmarkdown::html_vignette:
    toc: true
    fig_width: 8
vignette: >
  %\VignetteIndexEntry{Creating blurbs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  
  
```{r}
library(blurb)
dp <- blurb::DataPipe(data_source_name = 'longley')
str(dp)
```

```{r}
viz <- Viz()

scene1 = Scene(data_pipe = dp, viz = viz, num_frames = 5, timeline_var = 'Year', timeline_var_type = 'numeric',
              y_var = 'GNP', x_var = 'Year')
  
str(scene1)

```

```{r}
bar_chart_template <- function(d, y_var, x_var){
  p <- ggplot2::ggplot(data = d, aes(y = !!rlang::sym(y_var),
                                     x = !!rlang::sym(x_var))) +
    geom_col()
  return(p)
}

viz2 <- Viz(template_fn = bar_chart_template)
scene2 <- Scene(data_pipe = dp, viz = viz2, num_frames = 5, timeline_var = 'Year', timeline_var_type =   'numeric', y_var = 'Unemployed', x_var = 'Armed.Forces')

```

```{r}

scene1 %>% prep_frames() -> scene1
scene1@frame_prep_info$commuted_timeline_val

scene2 %>% prep_frames() -> scene2
scene2@frame_prep_info$commuted_timeline_val


```
```{r}
scene1 %>% generate_frames(y_var = "GNP", x_var = "Year") -> scene1
scene1 %>% render_frames(y_var = 'GNP', x_var = 'Year') -> scene1

scene2 %>% generate_frames(y_var = "Unemployed", x_var = "Armed.Forces") -> scene2
scene2 %>% render_frames(y_var = 'Unemployed', x_var = 'Armed.Forces') -> scene2

```


```{r}
b <- Blurb()
b %>% add_scenes(scenes_list = list(scene1, scene2)) -> b

```

```{r}
#b %>% make_blurb(width = 600, height = 400, res = 100)
```

